import {
  Banknote,
  Building2,
  CreditCard,
  Database,
  FileClock,
  KeyRound,
  Landmark,
  RadioTower,
  ShieldCheck,
  User,
  Wallet,
} from "lucide-react";
import type { EndpointCategory, EndpointSpec } from "../types/api";

export const ids = {
  accountId: "0194fd70-0000-7000-8000-000000000101",
  apiKeyId: "0194fd70-0000-7000-8000-000000000301",
  boletoId: "0194fd70-0000-7000-8000-000000000751",
  cardId: "0194fd70-0000-7000-8000-000000000801",
  contractId: "0194fd70-0000-7000-8000-000000000601",
  customerId: "0194fd70-0000-7000-8000-000000000001",
  externalAccountId: "0194fd70-0000-7000-8000-000000000501",
  feeId: "0194fd70-0000-7000-8000-000000000901",
  installmentId: "0194fd70-0000-7000-8000-000000000602",
  movementId: "0194fd70-0000-7000-8000-000000000401",
  offerId: "0194fd70-0000-7000-8000-000000000603",
  pixKeyId: "0194fd70-0000-7000-8000-000000000701",
  productId: "0194fd70-0000-7000-8000-000000000201",
  reconciliationRunId: "0194fd70-0000-7000-8000-000000001001",
  statementId: "0194fd70-0000-7000-8000-000000000351",
  transactionId: "0194fd70-0000-7000-8000-000000000111",
  transferId: "0194fd70-0000-7000-8000-000000000402",
  webhookDeliveryId: "0194fd70-0000-7000-8000-000000001101",
  webhookEndpointId: "0194fd70-0000-7000-8000-000000001102",
};

const moneyNotes = [
  "Valores monetários devem ir como string inteira em minor units, por exemplo \"1000\" para 10,00.",
  "Não use decimal nem float; o backend converte para bigint e preserva precisão financeira.",
];

const tenantNotes = [
  "Requer `x-api-key`; o tenant é resolvido antes do controller.",
  "A resposta pertence ao tenant autenticado, respeitando o contexto multi-tenant do backend.",
];

const sandboxNotes = [
  "Fluxo sandbox determinístico para desenvolvimento e demonstração técnica.",
  "Não representa integração real com banco, arranjo de pagamento, registradora, SPI ou processadora.",
];

const idempotencyNotes = [
  "Use uma chave nova por operação financeira real.",
  "Reutilize a mesma chave apenas para retry do mesmo payload.",
];

function endpoint(spec: EndpointSpec): EndpointSpec {
  return spec;
}

export const endpointSpec: EndpointCategory[] = [
  {
    category: "Autenticação",
    icon: ShieldCheck,
    endpoints: [
      endpoint({
        id: "login",
        method: "POST",
        path: "/v1/auth/login",
        title: "Login humano",
        description:
          "Cria uma sessão de usuário do tenant usando email e senha, mantendo API key como autenticação machine-to-machine do tenant.",
        details: [
          "Use quando quiser testar rotas que dependem de bearer token ou capturar identidade humana.",
          "A API key continua sendo enviada em header; usuário e tenant são conceitos separados.",
          "O console captura `access_token` automaticamente quando a resposta contém esse campo.",
        ],
        requestNotes: ["Informe o email e a senha do usuário de desenvolvimento."],
        responseNotes: [
          "Resposta bem-sucedida deve trazer dados de sessão ou token utilizável pelo painel.",
          "Falha de credencial deve retornar erro autenticável sem vazar detalhes sensíveis.",
        ],
        simpleFields: [
          { name: "email", label: "Email", type: "email", defaultValue: "admin@example.com" },
          { name: "password", label: "Senha", type: "text", defaultValue: "dev-password" },
        ],
        bodyTemplate: { email: "admin@example.com", password: "dev-password" },
        captures: "accessToken",
      }),
      endpoint({
        id: "refresh_session",
        method: "POST",
        path: "/v1/auth/refresh",
        title: "Refresh de sessão",
        description:
          "Renova uma sessão humana quando o backend recebe um refresh token válido no payload.",
        details: [
          "Use para validar ciclo de vida de sessão sem refazer login com senha.",
          "Mantém a separação entre sessão humana e API key do tenant.",
        ],
        requestNotes: ["O token de refresh deve ser obtido em fluxo de login quando exposto."],
        responseNotes: ["Pode retornar novo access token e/ou novos dados de sessão."],
        bodyTemplate: { refresh_token: "refresh-token-from-login" },
        captures: "accessToken",
      }),
      endpoint({
        id: "logout",
        method: "POST",
        path: "/v1/auth/logout",
        title: "Logout",
        description: "Encerra a sessão humana atual ou a sessão indicada pelo payload.",
        details: [
          "Use para invalidar sessão e confirmar que rotas com bearer deixam de aceitar o token.",
          "Não revoga a API key do tenant; isso fica em `/v1/api-keys/:id/revoke`.",
        ],
        requestNotes: ["Envie bearer token no ambiente do console quando quiser encerrar a sessão atual."],
        responseNotes: ["Resposta deve confirmar encerramento sem retornar segredo novo."],
        bodyTemplate: {},
      }),
      endpoint({
        id: "me",
        method: "GET",
        path: "/v1/auth/me",
        title: "Usuário atual",
        description: "Consulta o usuário autenticado pelo bearer token configurado no ambiente.",
        details: [
          "Use depois do login para confirmar que o access token foi capturado corretamente.",
          "Ajuda a diferenciar falhas de API key de falhas de bearer token.",
        ],
        requestNotes: ["Preencha Bearer Token no painel Ambiente ou execute login antes."],
        responseNotes: ["Deve retornar identidade e contexto do usuário autenticado."],
      }),
    ],
  },
  {
    category: "API Keys",
    icon: KeyRound,
    endpoints: [
      endpoint({
        id: "tenant",
        method: "GET",
        path: "/v1/tenant",
        title: "Tenant atual",
        description: "Retorna o tenant resolvido a partir da API key enviada no header.",
        details: [
          "Use como primeiro teste para confirmar que `x-api-key` está correto.",
          "É a rota mais simples para validar o isolamento multi-tenant.",
        ],
        requestNotes: tenantNotes,
        responseNotes: ["Retorna o identificador do tenant ativo."],
      }),
      endpoint({
        id: "list_keys",
        method: "GET",
        path: "/v1/api-keys",
        title: "Listar API keys",
        description: "Lista chaves machine-to-machine associadas ao tenant autenticado.",
        details: [
          "Use para auditar chaves existentes, status e metadados de plataforma.",
          "Segredos completos não devem ser retornados em listagem.",
        ],
        requestNotes: tenantNotes,
        responseNotes: ["Deve retornar chaves com dados seguros de exibição."],
      }),
      endpoint({
        id: "create_key",
        method: "POST",
        path: "/v1/api-keys",
        title: "Criar API key",
        description: "Cria uma nova chave machine-to-machine para integrações do tenant.",
        details: [
          "Use para simular governança de acesso de sistemas externos.",
          "A chave secreta deve ser tratada como valor retornado uma única vez.",
        ],
        requestNotes: ["Scopes definem a intenção de acesso da chave.", ...tenantNotes],
        responseNotes: ["Guarde o segredo retornado; listagens futuras não devem revelar o valor bruto."],
        bodyTemplate: { name: "Console Key", scopes: ["*"], metadata: { owner: "demo-console" } },
      }),
      endpoint({
        id: "revoke_key",
        method: "POST",
        path: `/v1/api-keys/${ids.apiKeyId}/revoke`,
        title: "Revogar API key",
        description: "Revoga uma API key para impedir novos acessos machine-to-machine.",
        details: [
          "Use quando uma chave foi comprometida, aposentada ou substituída.",
          "A revogação não encerra sessões humanas; ela afeta autenticação por API key.",
        ],
        requestNotes: ["Substitua o ID pelo ID real retornado em criação/listagem."],
        responseNotes: ["Deve retornar confirmação ou estado atualizado da chave."],
        bodyTemplate: { reason: "Rotina operacional de segurança" },
      }),
      endpoint({
        id: "rotate_key",
        method: "POST",
        path: `/v1/api-keys/${ids.apiKeyId}/rotate`,
        title: "Rotacionar API key",
        description: "Gera nova credencial para uma chave, preservando governança do tenant.",
        details: [
          "Use para renovar segredo sem recriar toda a intenção de integração.",
          "Rotação é uma operação sensível; trate o novo segredo como valor de exibição única.",
        ],
        requestNotes: ["Substitua o ID pelo ID real da chave ativa."],
        responseNotes: ["A resposta pode conter o novo segredo; não registre esse valor em logs."],
        bodyTemplate: { reason: "Rotação periódica" },
      }),
    ],
  },
  {
    category: "Customers",
    icon: User,
    endpoints: [
      endpoint({
        id: "create_customer",
        method: "POST",
        path: "/v1/customers",
        title: "Criar customer",
        description: "Cria pessoa física ou jurídica que pode possuir contas e produtos financeiros.",
        details: [
          "É o ponto inicial de onboarding para contas, instrumentos, consentimentos e lending.",
          "Modela dados cadastrais básicos; KYC/KYB externo real não está integrado.",
        ],
        requestNotes: ["`type` aceita `individual` ou `business`.", "Metadata permite dados auxiliares não críticos."],
        responseNotes: ["O console captura o `id` retornado como Customer do ambiente."],
        simpleFields: [
          { name: "type", label: "Tipo", type: "select", options: ["individual", "business"], defaultValue: "individual" },
          { name: "name", label: "Nome", type: "text", defaultValue: "Sandbox Customer" },
          { name: "email", label: "Email", type: "email", defaultValue: "sandbox@example.com" },
          { name: "document", label: "Documento", type: "text", defaultValue: "12345678900" },
        ],
        bodyTemplate: {
          type: "individual",
          name: "Sandbox Customer",
          email: "sandbox@example.com",
          document: "12345678900",
          metadata: { source: "demo-console" },
        },
        captures: "customerId",
      }),
      endpoint({
        id: "list_customers",
        method: "GET",
        path: "/v1/customers",
        title: "Listar customers",
        description: "Lista customers do tenant autenticado para navegação e auditoria operacional.",
        details: [
          "Use para encontrar IDs que serão usados em contas, instrumentos e compliance.",
          "A listagem é escopada pelo tenant resolvido pela API key.",
        ],
        requestNotes: tenantNotes,
        responseNotes: ["Retorna coleção de customers em ordem definida pelo backend."],
      }),
      endpoint({
        id: "get_customer",
        method: "GET",
        path: `/v1/customers/${ids.customerId}`,
        title: "Buscar customer",
        description: "Consulta os detalhes de um customer específico.",
        details: ["Use quando precisar validar status, metadata e dados cadastrais antes de criar produtos."],
        requestNotes: ["Troque o ID pelo customer capturado no ambiente."],
        responseNotes: ["Retorna o customer ou erro 404 quando não existe no tenant."],
      }),
      endpoint({
        id: "update_customer",
        method: "PATCH",
        path: `/v1/customers/${ids.customerId}`,
        title: "Atualizar customer",
        description: "Atualiza campos mutáveis do cadastro do customer.",
        details: [
          "Use para corrigir dados operacionais sem alterar histórico financeiro.",
          "Mudanças sensíveis devem ser auditáveis no contexto da API.",
        ],
        requestNotes: ["Envie apenas campos que devem mudar."],
        responseNotes: ["Retorna o customer atualizado."],
        bodyTemplate: {
          name: "Sandbox Customer Updated",
          email: "sandbox.updated@example.com",
          metadata: { reviewed: true },
        },
      }),
      endpoint({
        id: "verify_customer",
        method: "POST",
        path: `/v1/customers/${ids.customerId}/verify`,
        title: "Verificar customer",
        description: "Marca customer como verificado dentro do modelo interno.",
        details: [
          "Representa uma transição interna de status.",
          "Não significa KYC/KYB real com provedor externo.",
        ],
        requestNotes: ["Use customer existente no tenant."],
        responseNotes: ["Retorna customer com status atualizado."],
        bodyTemplate: { reason: "Verificação sandbox" },
      }),
      endpoint({
        id: "block_customer",
        method: "POST",
        path: `/v1/customers/${ids.customerId}/block`,
        title: "Bloquear customer",
        description: "Bloqueia customer por motivo operacional, risco ou compliance.",
        details: [
          "Use para simular postura de risco sem apagar dados.",
          "Histórico financeiro deve permanecer preservado.",
        ],
        requestNotes: ["Inclua motivo claro para auditoria."],
        responseNotes: ["Retorna estado atualizado ou confirmação de bloqueio."],
        bodyTemplate: { reason: "Bloqueio operacional sandbox" },
      }),
      endpoint({
        id: "archive_customer",
        method: "POST",
        path: `/v1/customers/${ids.customerId}/archive`,
        title: "Arquivar customer",
        description: "Arquiva customer sem remover registros financeiros imutáveis.",
        details: [
          "Use para encerramento administrativo de cadastro.",
          "Não substitui anonimização nem exclusão legalmente orientada.",
        ],
        requestNotes: ["Arquivamento deve ter razão de negócio."],
        responseNotes: ["Retorna customer com status arquivado quando aplicável."],
        bodyTemplate: { reason: "Encerramento de relacionamento sandbox" },
      }),
      endpoint({
        id: "create_consent",
        method: "POST",
        path: `/v1/customers/${ids.customerId}/consents`,
        title: "Registrar consentimento",
        description: "Registra aceite, revogação ou referência de consentimento do customer.",
        details: [
          "Use para rastrear termos, políticas e autorizações de uso de dados.",
          "É uma modelagem interna de consentimento, não um CMP externo.",
        ],
        requestNotes: ["Inclua tipo, versão e estado do consentimento."],
        responseNotes: ["Retorna registro criado para auditoria futura."],
        bodyTemplate: { type: "terms", version: "2026-05", accepted: true, metadata: {} },
      }),
      endpoint({
        id: "list_consents",
        method: "GET",
        path: `/v1/customers/${ids.customerId}/consents`,
        title: "Listar consentimentos",
        description: "Lista consentimentos associados a um customer.",
        details: ["Use em fluxos de auditoria, compliance e suporte ao usuário."],
        requestNotes: ["Use ID de customer do tenant atual."],
        responseNotes: ["Retorna histórico de consentimentos registrados."],
      }),
    ],
  },
  {
    category: "Accounts",
    icon: Wallet,
    endpoints: [
      endpoint({
        id: "create_account",
        method: "POST",
        path: "/v1/accounts",
        title: "Criar ledger account",
        description: "Cria uma conta contábil de ledger associável a customer e produtos financeiros.",
        details: [
          "Esta conta é a superfície contábil usada por entries e balances.",
          "Não confunda com `financial_accounts`, que representa a relação de produto/wallet.",
        ],
        requestNotes: ["`direction` define semântica contábil da conta.", ...moneyNotes],
        responseNotes: ["O console captura o `id` retornado como Account do ambiente."],
        simpleFields: [
          { name: "customer_id", label: "Customer ID", type: "text", defaultValue: "" },
          { name: "name", label: "Nome", type: "text", defaultValue: "Sandbox Wallet" },
          { name: "direction", label: "Direção", type: "select", options: ["debit", "credit"], defaultValue: "credit" },
        ],
        bodyTemplate: { customer_id: "", name: "Sandbox Wallet", direction: "credit", balance_minor: "0", metadata: {} },
        captures: "accountId",
      }),
      endpoint({
        id: "list_accounts",
        method: "GET",
        path: "/v1/accounts",
        title: "Listar accounts",
        description: "Lista contas de ledger do tenant para selecionar IDs e verificar status.",
        details: ["Use para encontrar contas que participarão de ledger, movimentos, holds e lending."],
        requestNotes: tenantNotes,
        responseNotes: ["Retorna contas com saldo, direção, status e metadata conforme backend."],
      }),
      endpoint({
        id: "get_account",
        method: "GET",
        path: `/v1/accounts/${ids.accountId}`,
        title: "Buscar account",
        description: "Consulta detalhes de uma conta de ledger específica.",
        details: ["Use para confirmar customer, direção contábil, status e metadata antes de movimentar dinheiro."],
        requestNotes: ["Substitua pelo Account ID capturado no painel Ambiente."],
        responseNotes: ["Retorna 404 se a conta não existir no tenant."],
      }),
      endpoint({
        id: "balance",
        method: "GET",
        path: `/v1/accounts/${ids.accountId}/balance`,
        title: "Consultar saldo",
        description: "Consulta saldo ledger/current, saldo disponível e valor reservado por holds.",
        details: [
          "É a rota correta para saldo bancário operacional no console.",
          "Saldo disponível considera reservas/holds quando existem.",
        ],
        requestNotes: ["Não envia body; usa Account ID no path."],
        responseNotes: ["Retorna campos de saldo como strings em minor units."],
      }),
      endpoint({
        id: "entries",
        method: "GET",
        path: `/v1/accounts/${ids.accountId}/entries`,
        title: "Entries da conta",
        description: "Lista lançamentos contábeis que afetam a conta.",
        details: [
          "Use para auditar como o saldo foi composto.",
          "Entries são a visão granular do ledger double-entry.",
        ],
        requestNotes: ["Não envia body."],
        responseNotes: ["Cada entry deve ter direção, valor e referência de transaction."],
      }),
      endpoint({
        id: "account_transactions",
        method: "GET",
        path: `/v1/accounts/${ids.accountId}/transactions`,
        title: "Transactions da conta",
        description: "Lista transactions que tocaram a conta por meio de entries.",
        details: ["Use quando quiser navegar do extrato contábil para os cabeçalhos de transaction."],
        responseNotes: ["Retorna transactions relacionadas à conta dentro do tenant."],
      }),
      endpoint({
        id: "freeze_account",
        method: "POST",
        path: `/v1/accounts/${ids.accountId}/freeze`,
        title: "Congelar conta",
        description: "Registra transição operacional para bloquear movimentações na conta.",
        details: ["Use em cenários de risco, compliance ou suporte para impedir novas movimentações."],
        requestNotes: ["Inclua motivo rastreável para auditoria."],
        responseNotes: ["Retorna transição com status anterior e novo status."],
        bodyTemplate: { reason: "Console freeze", metadata: {} },
      }),
      endpoint({
        id: "unfreeze_account",
        method: "POST",
        path: `/v1/accounts/${ids.accountId}/unfreeze`,
        title: "Reativar conta",
        description: "Remove bloqueio operacional e retorna a conta ao estado ativo.",
        details: ["Use apenas depois de resolver a causa do congelamento."],
        requestNotes: ["Inclua motivo de reativação."],
        responseNotes: ["Retorna transição operacional auditável."],
        bodyTemplate: { reason: "Console unfreeze", metadata: {} },
      }),
      endpoint({
        id: "close_account",
        method: "POST",
        path: `/v1/accounts/${ids.accountId}/close`,
        title: "Fechar conta",
        description: "Encerra/bloqueia a conta de forma operacional.",
        details: [
          "Use para encerramento administrativo.",
          "Não apaga histórico de ledger, entries ou audit logs.",
        ],
        requestNotes: ["Confirme saldo e reservas antes do fechamento em fluxos reais."],
        responseNotes: ["Retorna transição de status."],
        bodyTemplate: { reason: "Console close", metadata: {} },
      }),
      endpoint({
        id: "get_limits",
        method: "GET",
        path: `/v1/accounts/${ids.accountId}/limits`,
        title: "Consultar limites",
        description: "Consulta limites diário, mensal e por transação de uma conta.",
        details: ["Use para verificar política operacional antes de criar movimentos."],
        responseNotes: ["Retorna limites como minor-unit strings e moeda ISO."],
      }),
      endpoint({
        id: "limits",
        method: "PATCH",
        path: `/v1/accounts/${ids.accountId}/limits`,
        title: "Definir limites",
        description: "Cria ou atualiza limites operacionais da conta.",
        details: [
          "Limites ajudam a preparar governança de movimentação por conta.",
          "A enforcement completa depende do fluxo de produto que consome esses limites.",
        ],
        requestNotes: moneyNotes,
        responseNotes: ["Retorna configuração persistida."],
        bodyTemplate: {
          daily_limit_minor: "100000",
          monthly_limit_minor: "1000000",
          per_transaction_limit_minor: "50000",
          currency: "BRL",
          metadata: {},
        },
      }),
      endpoint({
        id: "create_statement",
        method: "POST",
        path: `/v1/accounts/${ids.accountId}/statements`,
        title: "Gerar statement",
        description: "Gera snapshot de extrato para um período informado.",
        details: [
          "Calcula abertura/fechamento a partir das entries do período.",
          "Serve como documento operacional imutável de consulta.",
        ],
        requestNotes: ["Use datas no formato `YYYY-MM-DD`."],
        responseNotes: ["Retorna statement com saldos e contagem de entries."],
        bodyTemplate: { period_start: "2026-05-01", period_end: "2026-05-31", metadata: {} },
      }),
      endpoint({
        id: "list_statements",
        method: "GET",
        path: `/v1/accounts/${ids.accountId}/statements`,
        title: "Listar statements",
        description: "Lista statements já gerados para uma conta.",
        details: ["Use para recuperar snapshots mensais ou períodos auditáveis."],
        responseNotes: ["Retorna lista de statements da conta no tenant."],
      }),
      endpoint({
        id: "get_statement",
        method: "GET",
        path: `/v1/statements/${ids.statementId}`,
        title: "Buscar statement",
        description: "Consulta um statement específico pelo ID.",
        details: ["Use quando uma UI ou processo operacional já possui o ID do extrato."],
        responseNotes: ["Retorna statement ou erro 404 se não existir."],
      }),
    ],
  },
  {
    category: "Financial Accounts",
    icon: Landmark,
    endpoints: [
      endpoint({
        id: "create_financial_account",
        method: "POST",
        path: "/v1/financial-accounts",
        title: "Criar financial account",
        description: "Cria a camada de produto/wallet associada a customer e account.",
        details: [
          "Use para separar experiência de produto da conta contábil do ledger.",
          "Ajuda a modelar wallets, contas de pagamento e outros produtos financeiros.",
        ],
        requestNotes: ["Informe customer/account quando o fluxo exigir associação."],
        responseNotes: ["Retorna financial account persistida."],
        bodyTemplate: { customer_id: "", account_id: "", type: "wallet", currency: "BRL", metadata: {} },
      }),
      endpoint({
        id: "list_financial_accounts",
        method: "GET",
        path: "/v1/financial-accounts",
        title: "Listar financial accounts",
        description: "Lista contas financeiras de produto do tenant.",
        details: ["Use para navegar objetos de wallet/produto sem olhar diretamente só para ledger."],
        responseNotes: ["Retorna financial accounts escopadas pelo tenant."],
      }),
      endpoint({
        id: "create_hold",
        method: "POST",
        path: "/v1/holds",
        title: "Criar hold",
        description: "Reserva parte do saldo disponível de uma conta.",
        details: [
          "Use para simular autorização, reserva ou bloqueio temporário.",
          "Hold influencia saldo disponível, mas não é uma entry de ledger por si só.",
        ],
        requestNotes: moneyNotes,
        responseNotes: ["Retorna hold com status inicial."],
        bodyTemplate: { account_id: "", amount_minor: "2500", reason: "Console hold", metadata: {} },
      }),
      endpoint({
        id: "list_holds",
        method: "GET",
        path: "/v1/holds",
        title: "Listar holds",
        description: "Lista reservas de saldo do tenant.",
        details: ["Use para auditar valores reservados que reduzem saldo disponível."],
        responseNotes: ["Retorna holds com status e valores em minor units."],
      }),
      endpoint({
        id: "release_hold",
        method: "POST",
        path: `/v1/holds/${ids.movementId}/release`,
        title: "Liberar hold",
        description: "Libera uma reserva sem capturá-la.",
        details: ["Use quando a autorização/reserva não deve mais afetar saldo disponível."],
        responseNotes: ["Retorna hold atualizado."],
        bodyTemplate: { reason: "Console release" },
      }),
      endpoint({
        id: "capture_hold",
        method: "POST",
        path: `/v1/holds/${ids.movementId}/capture`,
        title: "Capturar hold",
        description: "Captura uma reserva, preparando fechamento operacional do valor reservado.",
        details: [
          "Use para simular autorização que virou captura.",
          "Captura sandbox registra o estado operacional e preserva a relação com o fluxo financeiro de teste.",
        ],
        requestNotes: moneyNotes,
        responseNotes: ["Retorna hold atualizado."],
        bodyTemplate: { amount_minor: "2500", reason: "Console capture" },
      }),
    ],
  },
  {
    category: "Ledger",
    icon: Database,
    endpoints: [
      endpoint({
        id: "create_transaction",
        method: "POST",
        path: "/v1/transactions",
        title: "Postar transaction",
        description: "Registra uma transaction double-entry balanceada com entries de débito e crédito.",
        details: [
          "É a rota contábil mais explícita da API.",
          "O backend valida que total de débitos fecha com total de créditos.",
          "Reversões devem ser feitas por endpoint próprio, não por edição da transaction.",
        ],
        requestNotes: [...moneyNotes, ...idempotencyNotes],
        responseNotes: ["Retorna transaction criada com entries e metadata."],
        idempotent: true,
        bodyTemplate: {
          description: "Console ledger posting",
          entries: [
            { account_id: ids.accountId, direction: "debit", amount_minor: "1000" },
            { account_id: ids.accountId, direction: "credit", amount_minor: "1000" },
          ],
          metadata: { source: "demo-console" },
        },
      }),
      endpoint({
        id: "transactions",
        method: "GET",
        path: "/v1/transactions",
        title: "Listar transactions",
        description: "Lista cabeçalhos de transactions double-entry do tenant.",
        details: ["Use para auditoria contábil em nível de transaction."],
        responseNotes: ["Entries detalhadas podem estar em endpoints de conta ou detalhe."],
      }),
      endpoint({
        id: "get_transaction",
        method: "GET",
        path: `/v1/transactions/${ids.transactionId}`,
        title: "Buscar transaction",
        description: "Consulta uma transaction específica pelo ID.",
        details: ["Use para investigar metadata, descrição e relacionamento com entries."],
        responseNotes: ["Retorna transaction ou erro 404."],
      }),
      endpoint({
        id: "reverse_transaction",
        method: "POST",
        path: `/v1/transactions/${ids.transactionId}/reverse`,
        title: "Reverter transaction",
        description: "Cria lançamentos compensatórios para desfazer uma transaction sem alterar histórico.",
        details: [
          "Preserva imutabilidade contábil.",
          "É o caminho correto para corrigir lançamento financeiro já postado.",
        ],
        requestNotes: ["Informe motivo para rastreabilidade.", ...idempotencyNotes],
        responseNotes: ["Retorna nova transaction de reversal."],
        idempotent: true,
        bodyTemplate: { reason: "Console reversal", metadata: {} },
      }),
    ],
  },
  {
    category: "Money Movement",
    icon: Banknote,
    endpoints: [
      endpoint({
        id: "create_transfer",
        method: "POST",
        path: "/v1/transfers",
        title: "Criar transfer",
        description: "Cria transferência interna simplificada entre contas.",
        details: [
          "Use para um fluxo mais direto que o lançamento manual de transaction.",
          "O objeto de transfer fica separado da transaction contábil resultante.",
        ],
        requestNotes: [...moneyNotes, ...idempotencyNotes],
        responseNotes: ["Retorna transfer com estado e IDs relacionados quando aplicável."],
        idempotent: true,
        bodyTemplate: {
          source_account_id: ids.accountId,
          destination_account_id: ids.accountId,
          amount_minor: "1000",
          description: "Console transfer",
          metadata: {},
        },
      }),
      endpoint({
        id: "list_transfers",
        method: "GET",
        path: "/v1/transfers",
        title: "Listar transfers",
        description: "Lista transferências internas do tenant.",
        details: ["Use para acompanhar objetos de transferência, não apenas ledger entries."],
        responseNotes: ["Retorna transfers com status operacional."],
      }),
      endpoint({
        id: "get_transfer",
        method: "GET",
        path: `/v1/transfers/${ids.transferId}`,
        title: "Buscar transfer",
        description: "Consulta transferência interna específica.",
        details: ["Use para investigar status, origem, destino, valor e transaction relacionada."],
        responseNotes: ["Retorna transfer ou 404."],
      }),
      ...[
        ["deposit", "POST", "/v1/deposits", "Depósito", "Cria entrada de fundos sandbox na conta de destino.", { destination_account_id: ids.accountId, amount_minor: "2500", description: "Console deposit" }],
        ["withdrawal", "POST", "/v1/withdrawals", "Saque", "Cria saída de fundos sandbox a partir da conta de origem.", { source_account_id: ids.accountId, amount_minor: "1500", description: "Console withdrawal" }],
        ["payment", "POST", "/v1/payments", "Pagamento", "Cria pagamento genérico com objeto operacional de movement.", { source_account_id: ids.accountId, amount_minor: "1000", description: "Console payment" }],
        ["internal_transfer", "POST", "/v1/internal-transfers", "Internal transfer", "Cria money movement especializado entre contas internas.", { source_account_id: ids.accountId, destination_account_id: ids.accountId, amount_minor: "1000", description: "Console internal transfer" }],
        ["inbound_transfer", "POST", "/v1/inbound-transfers", "Inbound transfer", "Cria entrada sandbox de rail externo para conta interna.", { destination_account_id: ids.accountId, amount_minor: "2000", description: "Console inbound transfer" }],
        ["outbound_transfer", "POST", "/v1/outbound-transfers", "Outbound transfer", "Cria saída sandbox de conta interna para rail externo.", { source_account_id: ids.accountId, amount_minor: "2000", description: "Console outbound transfer" }],
        ["refund", "POST", "/v1/refunds", "Refund", "Cria refund sandbox para exercitar retorno financeiro.", { source_account_id: ids.accountId, destination_account_id: ids.accountId, amount_minor: "500", description: "Console refund" }],
      ].map(([id, method, path, title, description, bodyTemplate]) =>
        endpoint({
          id: String(id),
          method: method as "POST",
          path: String(path),
          title: String(title),
          description: String(description),
          details: [
            "Cria um objeto de money movement com estado operacional.",
            "Pode acionar ledger, eventos, auditoria e reconciliação conforme implementação.",
          ],
          requestNotes: [...moneyNotes, ...idempotencyNotes],
          responseNotes: ["Retorna movement ou objeto relacionado com status operacional."],
          idempotent: true,
          bodyTemplate: bodyTemplate as Record<string, unknown>,
        }),
      ),
      endpoint({
        id: "movements",
        method: "GET",
        path: "/v1/money-movements",
        title: "Listar movements",
        description: "Lista objetos de movimentação financeira do tenant.",
        details: ["Use para acompanhar ciclo de vida operacional de deposits, payments, transfers e refunds."],
        responseNotes: ["Retorna movements com tipo, status, valor e metadata."],
      }),
      endpoint({
        id: "get_movement",
        method: "GET",
        path: `/v1/money-movements/${ids.movementId}`,
        title: "Buscar movement",
        description: "Consulta um money movement específico.",
        details: ["Use para investigar status operacional antes de aprovar, falhar, retornar ou cancelar."],
        responseNotes: ["Retorna movement ou erro 404."],
      }),
      ...[
        ["approve_movement", "approve", "Aprovar movement", "Marca movement como posted para simular sucesso operacional."],
        ["fail_movement", "fail", "Falhar movement", "Marca movement como failed para simular erro operacional."],
        ["return_movement", "return", "Retornar movement", "Marca movement como returned para simular devolução/retorno."],
        ["cancel_movement", "cancel", "Cancelar movement", "Marca movement como canceled quando não deve seguir processamento."],
      ].map(([id, action, title, description]) =>
        endpoint({
          id,
          method: "POST",
          path: `/v1/money-movements/${ids.movementId}/${action}`,
          title,
          description,
          details: [
            "Endpoint de transição/test helper para ciclo de vida de movement.",
            "Útil para exercitar eventos, audit logs, webhooks e reconciliação sem provider real.",
          ],
          requestNotes: ["Substitua o Movement ID por um ID real retornado em criação/listagem."],
          responseNotes: ["Retorna movement atualizado ou confirmação de transição."],
          bodyTemplate: { reason: `Console ${action}` },
        }),
      ),
    ],
  },
  {
    category: "Financial Products",
    icon: Landmark,
    endpoints: [
      endpoint({
        id: "external_account",
        method: "POST",
        path: "/v1/external-accounts",
        title: "Criar external account",
        description: "Cadastra instrumento externo semelhante a conta bancária para fluxos financeiros.",
        details: [
          "Use para modelar origem/destino externo sem integração bancária real.",
          "Dados sensíveis usam postura de tokenização/mascaramento definida pelo domínio.",
        ],
        requestNotes: ["Associe customer quando disponível."],
        responseNotes: ["Retorna external account com status inicial."],
        bodyTemplate: {
          customer_id: "",
          holder_name: "Sandbox Holder",
          institution_name: "Sandbox Bank",
          account_number_last4: "1234",
          routing_number: "00000000",
          metadata: {},
        },
      }),
      endpoint({
        id: "list_external",
        method: "GET",
        path: "/v1/external-accounts",
        title: "Listar external accounts",
        description: "Lista contas externas cadastradas no tenant.",
        details: ["Use para selecionar instrumentos em outbound/inbound ou payment methods."],
        responseNotes: ["Retorna dados seguros de exibição."],
      }),
      endpoint({
        id: "verify_external",
        method: "POST",
        path: `/v1/external-accounts/${ids.externalAccountId}/verify`,
        title: "Verificar external account",
        description: "Executa verificação sandbox determinística de uma conta externa.",
        details: sandboxNotes,
        requestNotes: ["Use ID real de external account."],
        responseNotes: ["Retorna instrumento com status atualizado."],
        bodyTemplate: { verification_code: "sandbox" },
      }),
      endpoint({
        id: "payment_method",
        method: "POST",
        path: "/v1/payment-methods",
        title: "Criar payment method",
        description: "Cria método de pagamento reutilizável e tokenizado para o tenant/customer.",
        details: [
          "Use para modelar instrumento que pode ser usado por fluxos de pagamento.",
          "Token é valor técnico de sandbox neste estágio.",
        ],
        requestNotes: ["Associe external_account_id quando aplicável."],
        responseNotes: ["Retorna payment method com tipo, token/status e metadata."],
        bodyTemplate: {
          customer_id: "",
          external_account_id: ids.externalAccountId,
          type: "generic_rail",
          label: "Sandbox Rail",
          token: "sandbox-token-12345678",
          metadata: {},
        },
      }),
      endpoint({
        id: "list_payment_methods",
        method: "GET",
        path: "/v1/payment-methods",
        title: "Listar payment methods",
        description: "Lista métodos de pagamento cadastrados.",
        details: ["Use para validar tokenização e associação com customer/instrumento externo."],
        responseNotes: ["Retorna métodos sem expor dados sensíveis além do necessário."],
      }),
    ],
  },
  {
    category: "Rails Sandbox",
    icon: Building2,
    endpoints: [
      ...[
        ["pix_key", "POST", "/v1/pix/keys", "Criar Pix key", "Cria chave Pix sandbox para uma conta.", { account_id: ids.accountId, key_type: "random", key_value: "sandbox-random-key", metadata: {} }],
        ["pix_keys", "GET", "/v1/pix/keys", "Listar Pix keys", "Lista chaves Pix sandbox.", undefined],
        ["pix_charge", "POST", "/v1/pix/charges", "Criar Pix charge", "Cria cobrança Pix sandbox.", { account_id: ids.accountId, pix_key_id: ids.pixKeyId, amount_minor: "2500", metadata: {} }],
        ["pix_charges", "GET", "/v1/pix/charges", "Listar Pix charges", "Lista cobranças Pix sandbox.", undefined],
        ["boleto", "POST", "/v1/boletos", "Emitir boleto", "Cria boleto sandbox com vencimento e valor.", { account_id: ids.accountId, amount_minor: "5000", due_date: "2026-06-30", metadata: {} }],
        ["boletos", "GET", "/v1/boletos", "Listar boletos", "Lista boletos sandbox.", undefined],
        ["card_product", "POST", "/v1/card-products", "Criar card product", "Cria produto de cartão sandbox com spend controls.", { name: "Console Card Product", spend_controls: { max_amount_minor: "100000" }, metadata: {} }],
        ["card_products", "GET", "/v1/card-products", "Listar card products", "Lista produtos de cartão sandbox.", undefined],
        ["card", "POST", "/v1/cards", "Criar card", "Cria cartão sandbox ligado a customer e conta.", { customer_id: "", account_id: ids.accountId, last4: "4242", metadata: {} }],
        ["cards", "GET", "/v1/cards", "Listar cards", "Lista cartões sandbox.", undefined],
        ["card_authorization", "POST", "/v1/card-authorizations", "Autorizar card", "Cria autorização sandbox de cartão.", { card_id: ids.cardId, account_id: ids.accountId, amount_minor: "1200", merchant: "Sandbox Store", metadata: {} }],
        ["card_authorizations", "GET", "/v1/card-authorizations", "Listar authorizations", "Lista autorizações sandbox de cartão.", undefined],
      ].map(([id, method, path, title, description, bodyTemplate]) =>
        endpoint({
          id: String(id),
          method: method as "GET" | "POST",
          path: String(path),
          title: String(title),
          description: String(description),
          details: sandboxNotes,
          requestNotes: bodyTemplate ? moneyNotes : ["Não envia body; use para inspeção do sandbox."],
          responseNotes: ["Retorna registros sandbox usados para testar UI, webhooks, auditoria e relatórios."],
          bodyTemplate: bodyTemplate as Record<string, unknown> | undefined,
        }),
      ),
    ],
  },
  {
    category: "Lending",
    icon: Banknote,
    endpoints: [
      endpoint({
        id: "create_lending_proposal",
        method: "POST",
        path: "/v1/lending/proposals",
        title: "Criar proposal",
        description: "Solicita decisão de crédito via saga que chama o scoring Python por gRPC.",
        details: [
          "Use para validar integração TypeScript -> gRPC -> Python.",
          "A decisão usa política determinística e registra resultado auditável.",
        ],
        requestNotes: [...moneyNotes, ...idempotencyNotes],
        responseNotes: ["Retorna aprovação/reprovação, limite e reason quando o scoring responde."],
        idempotent: true,
        bodyTemplate: { account_id: ids.accountId, requested_amount_minor: "50000", metadata: {} },
      }),
      endpoint({
        id: "list_lending_proposals",
        method: "GET",
        path: "/v1/lending/proposals",
        title: "Listar proposals",
        description: "Lista propostas de lending criadas pelo fluxo de scoring.",
        details: ["Use para auditar decisões de crédito e motivos."],
        responseNotes: ["Retorna proposals com status e snapshot de decisão."],
      }),
      endpoint({
        id: "get_lending_proposal",
        method: "GET",
        path: `/v1/lending/proposals/${ids.productId}`,
        title: "Buscar proposal",
        description: "Consulta uma proposta de lending específica.",
        details: ["Use para investigar decisão individual de crédito."],
        responseNotes: ["Retorna proposal ou 404."],
      }),
      endpoint({
        id: "create_loan_product",
        method: "POST",
        path: "/v1/lending/products",
        title: "Criar produto de crédito",
        description: "Cria produto de lending com juros, limites e quantidade de parcelas.",
        details: ["Use antes de simular applications/offers por produto."],
        requestNotes: moneyNotes,
        responseNotes: ["Retorna produto criado e capturável para simulação."],
        bodyTemplate: {
          name: "Console Loan",
          annual_interest_bps: 2400,
          min_amount_minor: "10000",
          max_amount_minor: "500000",
          min_installments: 1,
          max_installments: 24,
          status: "active",
          metadata: {},
        },
        captures: "productId",
      }),
      endpoint({
        id: "products",
        method: "GET",
        path: "/v1/lending/products",
        title: "Produtos de crédito",
        description: "Lista produtos de lending disponíveis no tenant.",
        details: ["Use para selecionar `product_id` em simulações e applications."],
        responseNotes: ["Retorna juros, limites e status do produto."],
      }),
      endpoint({
        id: "simulation",
        method: "POST",
        path: "/v1/lending/simulations",
        title: "Simular crédito",
        description: "Calcula total e parcela sem contratar nem desembolsar.",
        details: [
          "Use para prever termos antes de application/offer.",
          "Simulação não cria contrato nem transaction de desembolso.",
        ],
        requestNotes: moneyNotes,
        responseNotes: ["Retorna principal, total, parcela, juros e número de installments."],
        bodyTemplate: { product_id: "", amount_minor: "50000", installments: 6 },
      }),
      endpoint({
        id: "create_application",
        method: "POST",
        path: "/v1/lending/applications",
        title: "Criar application",
        description: "Cria application e offer a partir de dados de crédito.",
        details: ["Use para simular etapa formal posterior à simulação."],
        requestNotes: moneyNotes,
        responseNotes: ["Retorna application e offer relacionados quando aprovado pelo fluxo."],
        bodyTemplate: {
          customer_id: "",
          account_id: ids.accountId,
          product_id: "",
          requested_amount_minor: "50000",
          installments: 6,
          metadata: {},
        },
      }),
      endpoint({
        id: "list_applications",
        method: "GET",
        path: "/v1/lending/applications",
        title: "Listar applications",
        description: "Lista applications de crédito do tenant.",
        details: ["Use para acompanhar status de solicitação e snapshot de scoring."],
        responseNotes: ["Retorna collection limitada de applications."],
      }),
      endpoint({
        id: "offers",
        method: "GET",
        path: "/v1/lending/offers",
        title: "Listar offers",
        description: "Lista ofertas disponíveis para aceite.",
        details: ["Use para encontrar offer_id antes de aceitar e criar contrato."],
        responseNotes: ["Retorna valores, parcelas, expiração e status."],
      }),
      endpoint({
        id: "accept_offer",
        method: "POST",
        path: `/v1/lending/offers/${ids.offerId}/accept`,
        title: "Aceitar offer",
        description: "Aceita uma offer, cria contrato e agenda installments.",
        details: [
          "É o ponto em que a simulação/oferta vira contrato operacional.",
          "Pode gerar transaction de desembolso conforme use case.",
        ],
        requestNotes: ["Use offer ativa e account de destino."],
        responseNotes: ["Retorna contrato criado ou erro se offer não for aceitável."],
        bodyTemplate: { account_id: ids.accountId, metadata: {} },
      }),
      endpoint({
        id: "list_contracts",
        method: "GET",
        path: "/v1/lending/contracts",
        title: "Listar contracts",
        description: "Lista contratos de crédito ativos/históricos do tenant.",
        details: ["Use para localizar contrato antes de consultar installments."],
        responseNotes: ["Retorna contratos com principal, total e status."],
      }),
      endpoint({
        id: "list_installments",
        method: "GET",
        path: `/v1/lending/contracts/${ids.contractId}/installments`,
        title: "Listar installments",
        description: "Lista parcelas de um contrato de crédito.",
        details: ["Use para identificar installment_id antes de pagamento."],
        responseNotes: ["Retorna parcelas com vencimento, principal, juros, total e status."],
      }),
      endpoint({
        id: "pay_installment",
        method: "POST",
        path: `/v1/lending/installments/${ids.installmentId}/pay`,
        title: "Pagar installment",
        description: "Registra pagamento de parcela de lending.",
        details: ["Pode criar transaction de pagamento e atualizar status da parcela."],
        requestNotes: [...moneyNotes, "Use account pagadora correta."],
        responseNotes: ["Retorna installment atualizado e referência financeira quando aplicável."],
        bodyTemplate: { account_id: ids.accountId, amount_minor: "10000", metadata: {} },
      }),
    ],
  },
  {
    category: "Fees",
    icon: CreditCard,
    endpoints: [
      endpoint({
        id: "fee_schedule",
        method: "POST",
        path: "/v1/fee-schedules",
        title: "Criar fee schedule",
        description: "Cria tabela de precificação por produto/rail.",
        details: ["Use para modelar monetização antes de cobrar fee."],
        requestNotes: moneyNotes,
        responseNotes: ["Retorna schedule criado."],
        bodyTemplate: {
          name: "Console Fees",
          product: "wallet",
          rail: "internal",
          fixed_amount_minor: "100",
          percent_bps: 0,
          min_amount_minor: "0",
          status: "active",
          metadata: {},
        },
      }),
      endpoint({
        id: "fee_schedules",
        method: "GET",
        path: "/v1/fee-schedules",
        title: "Listar fee schedules",
        description: "Lista tabelas de precificação do tenant.",
        details: ["Use para selecionar fee_schedule_id para cobrança."],
        responseNotes: ["Retorna schedules com produto, rail, valores e status."],
      }),
      endpoint({
        id: "pricing_rule",
        method: "POST",
        path: "/v1/pricing-rules",
        title: "Criar pricing rule",
        description: "Cria regra de preço por produto, rail e faixa de valor.",
        details: ["Use quando precisar granularidade maior que uma tabela simples."],
        requestNotes: moneyNotes,
        responseNotes: ["Retorna rule criada."],
        bodyTemplate: {
          product: "wallet",
          rail: "pix",
          min_amount_minor: "0",
          fixed_amount_minor: "75",
          percent_bps: 10,
          status: "active",
          metadata: {},
        },
      }),
      endpoint({
        id: "pricing_rules",
        method: "GET",
        path: "/v1/pricing-rules",
        title: "Listar pricing rules",
        description: "Lista regras de pricing do tenant.",
        details: ["Use para auditar preço efetivo por produto/rail."],
        responseNotes: ["Retorna regras ativas/inativas conforme backend."],
      }),
      endpoint({
        id: "fee_charge",
        method: "POST",
        path: "/v1/fees",
        title: "Cobrar fee",
        description: "Cobra taxa e registra entries separadas no ledger quando aplicável.",
        details: [
          "Use para testar monetização financeira rastreável.",
          "Fee deve ser reversível e auditável.",
        ],
        requestNotes: [...moneyNotes, ...idempotencyNotes],
        responseNotes: ["Retorna fee cobrada e referências contábeis."],
        idempotent: true,
        bodyTemplate: {
          fee_schedule_id: ids.feeId,
          account_id: ids.accountId,
          amount_minor: "100",
          description: "Console fee",
          metadata: {},
        },
      }),
      endpoint({
        id: "fees",
        method: "GET",
        path: "/v1/fees",
        title: "Listar fees",
        description: "Lista taxas cobradas no tenant.",
        details: ["Use para conciliar receita, reversals e entries de taxa."],
        responseNotes: ["Retorna fees com status e metadata."],
      }),
      endpoint({
        id: "fee_reverse",
        method: "POST",
        path: `/v1/fees/${ids.feeId}/reverse`,
        title: "Estornar fee",
        description: "Cria lançamento reverso de uma fee cobrada.",
        details: ["Use quando uma taxa precisa ser compensada sem apagar histórico."],
        requestNotes: idempotencyNotes,
        responseNotes: ["Retorna fee/reversal resultante."],
        idempotent: true,
        bodyTemplate: { reason: "Console fee reversal" },
      }),
    ],
  },
  {
    category: "Eventos e Auditoria",
    icon: RadioTower,
    endpoints: [
      endpoint({
        id: "events",
        method: "GET",
        path: "/v1/events",
        title: "Eventos",
        description: "Lista eventos de domínio persistidos para o tenant.",
        details: ["Use para verificar se comandos geraram eventos esperados."],
        responseNotes: ["Retorna tipo, resource e payload do evento."],
      }),
      endpoint({
        id: "audit",
        method: "GET",
        path: "/v1/audit-logs",
        title: "Audit logs",
        description: "Lista registros de auditoria operacional capturados pelo middleware.",
        details: ["Use para correlacionar request_id, tenant, usuário, rota e comando."],
        responseNotes: ["Retorna trilha de auditoria sem expor segredos."],
      }),
      endpoint({
        id: "webhooks",
        method: "GET",
        path: "/v1/webhook-endpoints",
        title: "Webhooks",
        description: "Lista endpoints de webhook cadastrados no tenant.",
        details: ["Use para auditar URLs, eventos inscritos e status."],
        responseNotes: ["Não deve retornar signing secret bruto em listagem."],
      }),
      endpoint({
        id: "create_webhook",
        method: "POST",
        path: "/v1/webhook-endpoints",
        title: "Criar webhook",
        description: "Cadastra endpoint externo para receber eventos assíncronos.",
        details: [
          "Cria segredo de assinatura para validar origem do payload.",
          "Eventos podem ser filtrados por lista ou `*`.",
        ],
        requestNotes: ["Use URL HTTPS real quando for testar entrega fora do sandbox."],
        responseNotes: ["O segredo pode ser retornado apenas na criação."],
        bodyTemplate: { url: "https://example.com/webhooks/financial-api", events: ["*"] },
      }),
      endpoint({
        id: "rotate_webhook_secret",
        method: "POST",
        path: `/v1/webhook-endpoints/${ids.webhookEndpointId}/rotate-secret`,
        title: "Rotacionar segredo",
        description: "Rotaciona o signing secret de um endpoint de webhook.",
        details: ["Use quando segredo foi exposto ou em rotação preventiva."],
        responseNotes: ["Retorna novo segredo de exibição sensível."],
        bodyTemplate: { reason: "Rotação operacional" },
      }),
      endpoint({
        id: "webhook_deliveries",
        method: "GET",
        path: "/v1/webhook-deliveries",
        title: "Webhook deliveries",
        description: "Lista tentativas de entrega de webhook com status operacional.",
        details: ["Use para investigar falhas, retries, dead-letter e latência de entrega."],
        responseNotes: ["Retorna status code, duração, erro e body truncado quando disponível."],
      }),
      endpoint({
        id: "retry_webhook_delivery",
        method: "POST",
        path: `/v1/webhook-deliveries/${ids.webhookDeliveryId}/retry`,
        title: "Retry delivery",
        description: "Reagenda uma entrega de webhook para nova tentativa.",
        details: ["Use depois de corrigir endpoint externo ou falha transitória."],
        requestNotes: ["Confirme que retry é seguro para o consumidor do webhook."],
        responseNotes: ["Retorna delivery em estado pending."],
        bodyTemplate: {},
      }),
      endpoint({
        id: "webhook_test_event",
        method: "POST",
        path: "/v1/webhook-test-events",
        title: "Evento teste webhook",
        description: "Cria evento sandbox para testar pipeline de events/webhooks.",
        details: ["Use para validar cadastro de webhook sem depender de fluxo financeiro real."],
        responseNotes: ["Retorna evento `webhook.test`."],
        bodyTemplate: {},
      }),
    ],
  },
  {
    category: "Reconciliation",
    icon: FileClock,
    endpoints: [
      endpoint({
        id: "create_reconciliation",
        method: "POST",
        path: "/v1/reconciliation-runs",
        title: "Rodar conciliação",
        description: "Cria reconciliation run para comparar ledger entries e money movements no período.",
        details: [
          "Registra run e item com status matched/difference.",
          "Atualiza métricas de conciliação para Grafana/Prometheus.",
        ],
        requestNotes: ["Use datas no formato `YYYY-MM-DD`."],
        responseNotes: ["Retorna resumo com contagens, totais e diferenças."],
        bodyTemplate: { period_start: "2026-05-01", period_end: "2026-05-31" },
      }),
      endpoint({
        id: "reconciliation_runs",
        method: "GET",
        path: "/v1/reconciliation-runs",
        title: "Listar conciliações",
        description: "Lista reconciliation runs criadas no tenant.",
        details: ["Use para acompanhar histórico de conciliações locais."],
        responseNotes: ["Retorna runs com período, status e summary."],
      }),
      endpoint({
        id: "reconciliation_items",
        method: "GET",
        path: `/v1/reconciliation-runs/${ids.reconciliationRunId}/items`,
        title: "Itens da conciliação",
        description: "Lista itens e diferenças de uma reconciliation run.",
        details: ["Use quando o summary indicar diferença e precisar investigar recurso/valor."],
        responseNotes: ["Retorna expected/actual amounts quando existirem."],
      }),
      endpoint({
        id: "report_balances",
        method: "GET",
        path: "/v1/reports/ledger-balances",
        title: "Report saldos",
        description: "Relatório operacional de saldos de ledger accounts.",
        details: ["Use para visão de tesouraria/operação por conta."],
        responseNotes: ["Retorna account_id, customer_id, status, saldo e metadata."],
      }),
      endpoint({
        id: "report_reconciliation",
        method: "GET",
        path: "/v1/reports/reconciliation",
        title: "Report conciliação",
        description: "Relatório consolidado das últimas runs de conciliação.",
        details: ["Use para painel operacional sem abrir run por run."],
        responseNotes: ["Retorna status, período, summary e timestamps."],
      }),
      endpoint({
        id: "report_outbox",
        method: "GET",
        path: "/v1/reports/outbox",
        title: "Report outbox",
        description: "Mostra itens e estados agregados da outbox.",
        details: ["Use para investigar eventos presos antes de RabbitMQ/webhooks."],
        responseNotes: ["Retorna status, total e item mais antigo por status."],
      }),
    ],
  },
  {
    category: "Compliance",
    icon: ShieldCheck,
    endpoints: [
      endpoint({
        id: "export_customer",
        method: "GET",
        path: `/v1/customers/${ids.customerId}/export`,
        title: "Exportar customer",
        description: "Exporta dados do customer para fluxo operacional de LGPD/suporte.",
        details: [
          "Use para inspecionar dados associados ao customer.",
          "Não é promessa de pacote jurídico completo; é superfície técnica de export.",
        ],
        responseNotes: ["Retorna dados exportáveis sem remover histórico financeiro."],
      }),
      endpoint({
        id: "anonymize_customer",
        method: "POST",
        path: `/v1/customers/${ids.customerId}/anonymize`,
        title: "Anonimizar customer",
        description: "Anonimiza PII possível mantendo restrições de histórico financeiro imutável.",
        details: [
          "Use para simular solicitação LGPD onde dados financeiros não podem ser apagados livremente.",
          "Não apaga transactions, entries ou audit logs.",
        ],
        requestNotes: ["Informe motivo claro."],
        responseNotes: ["Retorna solicitação/resultado de anonimização."],
        bodyTemplate: { reason: "Solicitação LGPD sandbox" },
      }),
      endpoint({
        id: "compliance_requests",
        method: "GET",
        path: "/v1/compliance-requests",
        title: "Compliance requests",
        description: "Lista solicitações de compliance registradas no tenant.",
        details: ["Use para acompanhar export/anonymize/retenção e histórico operacional."],
        responseNotes: ["Retorna requests com domínio, status e timestamps."],
      }),
      endpoint({
        id: "retention_policy",
        method: "POST",
        path: "/v1/data-retention-policies",
        title: "Salvar retenção",
        description: "Cria ou atualiza política de retenção por domínio.",
        details: [
          "Use para modelar governança de ciclo de vida de dados.",
          "Não substitui revisão jurídica/regulatória.",
        ],
        requestNotes: ["Informe domínio, quantidade de dias e ação pretendida."],
        responseNotes: ["Retorna policy persistida."],
        bodyTemplate: { domain: "customers", retention_days: 1825, action: "review", metadata: {} },
      }),
      endpoint({
        id: "retention_policies",
        method: "GET",
        path: "/v1/data-retention-policies",
        title: "Listar retenções",
        description: "Lista políticas de retenção por domínio.",
        details: ["Use para auditar postura de retenção do tenant."],
        responseNotes: ["Retorna domínio, prazo e ação configurada."],
      }),
    ],
  },
  {
    category: "Operacional",
    icon: FileClock,
    endpoints: [
      endpoint({
        id: "health",
        method: "GET",
        path: "/health",
        title: "Health",
        description: "Liveness check do core API.",
        details: ["Use para saber se o processo HTTP está vivo."],
        responseNotes: ["Deve ser barato, público e adequado para checagem simples."],
      }),
      endpoint({
        id: "ready",
        method: "GET",
        path: "/ready",
        title: "Ready",
        description: "Readiness check com postura de dependências.",
        details: ["Use antes de enviar tráfego real para o serviço."],
        responseNotes: ["Falha quando dependência essencial impede operação."],
      }),
      endpoint({
        id: "metrics",
        method: "GET",
        path: "/metrics",
        title: "Metrics",
        description: "Exposição Prometheus com métricas HTTP, domínio, idempotência e conciliação.",
        details: ["Use para validar sinais usados pelo Grafana e alertas Prometheus."],
        responseNotes: ["Retorna texto no formato Prometheus."],
      }),
      endpoint({
        id: "openapi",
        method: "GET",
        path: "/openapi.json",
        title: "OpenAPI",
        description: "Contrato OpenAPI 3.1 atual da API.",
        details: ["Use para inspecionar paths, schemas e versionamento público."],
        responseNotes: ["Retorna documento JSON versionado."],
      }),
    ],
  },
];
